// Code generated by tygo. DO NOT EDIT.

//////////
// source: types.go
/*
Package contracts is the SINGLE SOURCE OF TRUTH for the data shapes shared
between the Go backend and the TypeScript extension/website.

You define types here once, in Go. Running `moon run contracts:generate`
(tygo) emits the matching TypeScript into packages/shared/src/types.gen.ts,
so the two languages can never drift apart.

Transport: chat is SSE (server -> client, GET /events) + POST (client ->
server, POST /chat). The types below describe that protocol.
*/

/**
 * AgentRole identifies who produced a message in a conversation.
 */
export type AgentRole = string;
export const RoleUser: AgentRole = "user";
export const RoleAssistant: AgentRole = "assistant";
export const RoleSystem: AgentRole = "system";
/**
 * ChatMessage is one turn in a Charli conversation (the UI's model).
 */
export interface ChatMessage {
  role: AgentRole;
  content: string;
}
/**
 * ChatRequest is the POST /chat body sent by the client (client -> server).
 */
export interface ChatRequest {
  session: string; // identifies the caller's SSE stream
  id: string; // correlates this message with its reply
  content: string;
}
/**
 * ChatEvent is a message pushed down the SSE stream (server -> client).
 */
export interface ChatEvent {
  type: string; // "chat" | "error"
  id: string; // matches the ChatRequest.ID it answers
  content: string;
}
