// Code generated by tygo. DO NOT EDIT.

//////////
// source: types.go
/*
Package contracts is the SINGLE SOURCE OF TRUTH for the data shapes
shared between the Go backend and the TypeScript extension/website.

You define types here once, in Go. Running `moon run contracts:generate`
(tygo) emits the matching TypeScript into packages/shared/src/types.gen.ts,
so the two languages can never drift apart.
*/

/**
 * AgentRole identifies who produced a message in a conversation.
 */
export type AgentRole = string;
export const RoleUser: AgentRole = "user";
export const RoleAssistant: AgentRole = "assistant";
export const RoleSystem: AgentRole = "system";
/**
 * ChatMessage is one turn in a Charli conversation.
 */
export interface ChatMessage {
  role: AgentRole;
  content: string;
}
/**
 * WSMessage is the envelope for every websocket frame exchanged
 * between the extension and the backend.
 */
export interface WSMessage {
  type: string; // e.g. "chat", "action", "ping"
  payload: any; // shape depends on Type
}
