// Code generated by tygo. DO NOT EDIT.

//////////
// source: types.go
/*
Package contracts is the SINGLE SOURCE OF TRUTH for the data shapes shared
between the Go backend and the TypeScript extension/website.

You define types here once, in Go. Running `moon run contracts:generate`
(tygo) emits the matching TypeScript into packages/shared/src/types.gen.ts,
so the two languages can never drift apart.

Transport: chat is SSE (server -> client, GET /events) + POST (client ->
server, POST /chat). The types below describe that protocol.
*/

/**
 * AgentRole identifies who produced a message in a conversation.
 */
export type AgentRole = string;
export const RoleUser: AgentRole = "user";
export const RoleAssistant: AgentRole = "assistant";
export const RoleSystem: AgentRole = "system";
/**
 * ChatMessage is one turn in a Charli conversation (the UI's model).
 */
export interface ChatMessage {
  role: AgentRole;
  content: string;
}
/**
 * ChatRequest is the POST /chat body sent by the client (client -> server).
 */
export interface ChatRequest {
  session: string; // identifies the caller's SSE stream
  id: string; // correlates this message with its reply
  content: string; // the user's message
  page?: string; // text of the page the user is viewing (L1)
}
/**
 * Action is something Charli proposes to do on the page (L2). The model selects
 * it; the backend safety engine decides whether it runs.
 */
export interface Action {
  kind: string; // "fill" | "click"
  value?: string; // text to type (fill)
  target?: string; // button/link text to click (click)
}
/**
 * ChatEvent is a message pushed down the SSE stream (server -> client).
 * 	type "chat"        a normal assistant answer (content)
 * 	type "error"       something went wrong (content)
 * 	type "action"      Charli proposes an action needing confirmation (action set)
 * 	type "execute"     an approved action to perform on the page (action set)
 * 	type "cancelled"   a rejected action
 * 	type "interrupted" the user stopped an in-progress multi-step task (L3)
 */
export interface ChatEvent {
  type: string;
  id: string; // matches the ChatRequest.ID it answers
  content: string;
  action?: Action;
}
/**
 * ConfirmRequest is the POST /confirm body: the user's decision on a proposed
 * action (client -> server).
 */
export interface ConfirmRequest {
  session: string;
  id: string;
  approved: boolean;
}
/**
 * ObserveRequest is the POST /observe body (L3): whether an approved action
 * actually succeeded when performed on the page, so the agent loop can
 * decide its next step (client -> server).
 */
export interface ObserveRequest {
  session: string;
  id: string;
  success: boolean;
  detail?: string; // e.g. why it failed
}
/**
 * InterruptRequest is the POST /interrupt body (L3): the user's kill switch,
 * stopping any in-progress multi-step task (client -> server).
 */
export interface InterruptRequest {
  session: string;
  id: string;
}
